# Generated by Django 5.1.7 on 2025-04-04 05:13

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoyolaSystem', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
