# Generated by Django 5.1.7 on 2025-04-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoyolaSystem', '0005_alter_announcement_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
