# Generated by Django 5.1.7 on 2025-04-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoyolaSystem', '0006_event_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
